# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - postgresql
  
addons:
  postgresql: "9.6"

php:
 - '7.0'

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files
    - .php_cs.cache

# Define an environment variable
env:
  - SYMFONY_VERSION="3.4.*" DB=postgresql

before_install:
  # Update Composer
  - composer self-update
  # Install Postgis
  - sudo apt-get install postgresql-9.6-postgis-2.3 -y -q
  # Create DB
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE travis_postgis to foo;' -U postgres -d travis_postgis


# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test --if-not-exists
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

# Run script
script:
  - vendor/bin/simple-phpunit --coverage-clover=coverage.xml
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation
  - bash <(curl -s https://codecov.io/bash)



