<?php

/*
 * This file is part of the ADFC Radschulwegplan Backend package.
 *
 * <https://github.com/ADFC-Hamburg/adfc-radschulwegplan-backend>
 *
 * (c) 2018 by James Twellmeyer <jet02@twellmeyer.eu>
 * (c) 2018 by Sven Anders <github2018@sven.anders.hamburg>
 *
 * Released under the GPL 3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Please also visit our (german) webpage about the project:
 *
 * <https://hamburg.adfc.de/verkehr/themen-a-z/kinder/schulwegplanung/>
 *
 */

namespace AppBundle\Repository;

/**
 * DangerPointRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DangerPointRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return only dangerPoints from a specific school.
     *
     * @param int $id SchoolId
     *
     * @return DangerPoint[]
     */
    public function findAllWithSchool(int $id)
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p FROM AppBundle:DangerPoint p JOIN p.createdBy u WHERE u.school= :sId ORDER BY p.id')
                    ->setParameter('sId', $id)
                    ->getResult();
    }
}
