<?php

namespace AppBundle\Repository;

/**
 * DangerPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DangerPointRepository extends \Doctrine\ORM\EntityRepository
{
}
