<?php

namespace AppBundle\Repository;

/**
 * SchoolWayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolWayRepository extends \Doctrine\ORM\EntityRepository
{
}
